# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Pod-Outline
version:      0.10
version_from: Outline.pm
installdirs:  site
requires:
    Pod::Usage:                    1.12
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.23
